stages:
  - build
  - test

build-job:
  stage: build
  tags:
    - docker
  script:
    - echo "Сборка проекта"
  needs: []

test-job:
  stage: test
  tags:
    - docker
  script:
    - echo "Запуск тестов"
  rules:
    - changes:
        - "*.go"